name: BingoReloaded # the plugins name as it should appear in the plugin list /pl
version: 4.0.0 # the plugin's version
author: Steven
main: io.github.steaf23.bingoreloaded.BingoReloadedPaper
api-version: 1.21.7
